@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2U4ZWMyNzk3OTc0YmM3ZTA1YmZjNiIsInJvbGUiOjEsImlhdCI6MTY1NzcwNDEzMH0.EaRGtA5mlxOtciPv8IPsFo69yYU9NHtTxGSWtpcU-b4

# @name signup

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "dung.tv",
  "password": "1234",
  "confirmPassword": "1234",
  "fullname": "Trần Văn Dũng",
  "group": 1,
  "role": 1
}

###

# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "dung.tv",
  "password": "1234"
}

###

# @name getMe
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}

###

# @name changePassword
PUT {{baseUrl}}/auth/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "123456",
  "newPassword": "1234",
  "confirmPassword": "1234"
}
