@baseUrl = http://localhost:5000
@sub = users

# @name getUsers
GET {{baseUrl}}/{{sub}}?_page=1&_limit=10

###

# @name addUser
POST {{baseUrl}}/{{sub}}
Content-Type: application/json

{
  "name": "Lê Văn Dũng",
  "role": "leader",
  "group": "3"
}

